modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://github.com/Faboslav/it-takes-a-pillage/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = '''
${modDescription}
'''
logoFile = "icon.png"
logoBlur = false
displayURL = "https://github.com/Faboslav/it-takes-a-pillage"

[modproperties.${ modId }]
catalogueImageIcon = "catalogue_icon.png"
catalogueBackground = "catalogue_background.png"
configuredBackground = "catalogue_background.png"